// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfresh/plasma/protobuf/stream.proto

package openfresh.plasma;

public interface EventTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EventType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
