// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfresh/plasma/protobuf/stream.proto

package openfresh.plasma;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.EventType eventType = 1;</code>
   */
  boolean hasEventType();
  /**
   * <code>.proto.EventType eventType = 1;</code>
   */
  openfresh.plasma.EventType getEventType();
  /**
   * <code>.proto.EventType eventType = 1;</code>
   */
  openfresh.plasma.EventTypeOrBuilder getEventTypeOrBuilder();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
