// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfresh/plasma/protobuf/stream.proto

package openfresh.plasma;

/**
 * Protobuf type {@code proto.Payload}
 */
public  final class Payload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Payload)
    PayloadOrBuilder {
  // Use Payload.newBuilder() to construct.
  private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payload() {
    data_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Payload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            openfresh.plasma.EventType.Builder subBuilder = null;
            if (eventType_ != null) {
              subBuilder = eventType_.toBuilder();
            }
            eventType_ = input.readMessage(openfresh.plasma.EventType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eventType_);
              eventType_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            data_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return openfresh.plasma.Stream.internal_static_proto_Payload_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return openfresh.plasma.Stream.internal_static_proto_Payload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            openfresh.plasma.Payload.class, openfresh.plasma.Payload.Builder.class);
  }

  public static final int EVENTTYPE_FIELD_NUMBER = 1;
  private openfresh.plasma.EventType eventType_;
  /**
   * <code>.proto.EventType eventType = 1;</code>
   */
  public boolean hasEventType() {
    return eventType_ != null;
  }
  /**
   * <code>.proto.EventType eventType = 1;</code>
   */
  public openfresh.plasma.EventType getEventType() {
    return eventType_ == null ? openfresh.plasma.EventType.getDefaultInstance() : eventType_;
  }
  /**
   * <code>.proto.EventType eventType = 1;</code>
   */
  public openfresh.plasma.EventTypeOrBuilder getEventTypeOrBuilder() {
    return getEventType();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private volatile java.lang.Object data_;
  /**
   * <code>string data = 2;</code>
   */
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventType_ != null) {
      output.writeMessage(1, getEventType());
    }
    if (!getDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEventType());
    }
    if (!getDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof openfresh.plasma.Payload)) {
      return super.equals(obj);
    }
    openfresh.plasma.Payload other = (openfresh.plasma.Payload) obj;

    boolean result = true;
    result = result && (hasEventType() == other.hasEventType());
    if (hasEventType()) {
      result = result && getEventType()
          .equals(other.getEventType());
    }
    result = result && getData()
        .equals(other.getData());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEventType()) {
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static openfresh.plasma.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static openfresh.plasma.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static openfresh.plasma.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static openfresh.plasma.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static openfresh.plasma.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static openfresh.plasma.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static openfresh.plasma.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static openfresh.plasma.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static openfresh.plasma.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static openfresh.plasma.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(openfresh.plasma.Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Payload)
      openfresh.plasma.PayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return openfresh.plasma.Stream.internal_static_proto_Payload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return openfresh.plasma.Stream.internal_static_proto_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              openfresh.plasma.Payload.class, openfresh.plasma.Payload.Builder.class);
    }

    // Construct using openfresh.plasma.Payload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (eventTypeBuilder_ == null) {
        eventType_ = null;
      } else {
        eventType_ = null;
        eventTypeBuilder_ = null;
      }
      data_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return openfresh.plasma.Stream.internal_static_proto_Payload_descriptor;
    }

    public openfresh.plasma.Payload getDefaultInstanceForType() {
      return openfresh.plasma.Payload.getDefaultInstance();
    }

    public openfresh.plasma.Payload build() {
      openfresh.plasma.Payload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public openfresh.plasma.Payload buildPartial() {
      openfresh.plasma.Payload result = new openfresh.plasma.Payload(this);
      if (eventTypeBuilder_ == null) {
        result.eventType_ = eventType_;
      } else {
        result.eventType_ = eventTypeBuilder_.build();
      }
      result.data_ = data_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof openfresh.plasma.Payload) {
        return mergeFrom((openfresh.plasma.Payload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(openfresh.plasma.Payload other) {
      if (other == openfresh.plasma.Payload.getDefaultInstance()) return this;
      if (other.hasEventType()) {
        mergeEventType(other.getEventType());
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      openfresh.plasma.Payload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (openfresh.plasma.Payload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private openfresh.plasma.EventType eventType_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        openfresh.plasma.EventType, openfresh.plasma.EventType.Builder, openfresh.plasma.EventTypeOrBuilder> eventTypeBuilder_;
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public boolean hasEventType() {
      return eventTypeBuilder_ != null || eventType_ != null;
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public openfresh.plasma.EventType getEventType() {
      if (eventTypeBuilder_ == null) {
        return eventType_ == null ? openfresh.plasma.EventType.getDefaultInstance() : eventType_;
      } else {
        return eventTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public Builder setEventType(openfresh.plasma.EventType value) {
      if (eventTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventType_ = value;
        onChanged();
      } else {
        eventTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public Builder setEventType(
        openfresh.plasma.EventType.Builder builderForValue) {
      if (eventTypeBuilder_ == null) {
        eventType_ = builderForValue.build();
        onChanged();
      } else {
        eventTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public Builder mergeEventType(openfresh.plasma.EventType value) {
      if (eventTypeBuilder_ == null) {
        if (eventType_ != null) {
          eventType_ =
            openfresh.plasma.EventType.newBuilder(eventType_).mergeFrom(value).buildPartial();
        } else {
          eventType_ = value;
        }
        onChanged();
      } else {
        eventTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public Builder clearEventType() {
      if (eventTypeBuilder_ == null) {
        eventType_ = null;
        onChanged();
      } else {
        eventType_ = null;
        eventTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public openfresh.plasma.EventType.Builder getEventTypeBuilder() {
      
      onChanged();
      return getEventTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    public openfresh.plasma.EventTypeOrBuilder getEventTypeOrBuilder() {
      if (eventTypeBuilder_ != null) {
        return eventTypeBuilder_.getMessageOrBuilder();
      } else {
        return eventType_ == null ?
            openfresh.plasma.EventType.getDefaultInstance() : eventType_;
      }
    }
    /**
     * <code>.proto.EventType eventType = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        openfresh.plasma.EventType, openfresh.plasma.EventType.Builder, openfresh.plasma.EventTypeOrBuilder> 
        getEventTypeFieldBuilder() {
      if (eventTypeBuilder_ == null) {
        eventTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            openfresh.plasma.EventType, openfresh.plasma.EventType.Builder, openfresh.plasma.EventTypeOrBuilder>(
                getEventType(),
                getParentForChildren(),
                isClean());
        eventType_ = null;
      }
      return eventTypeBuilder_;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 2;</code>
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 2;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <code>string data = 2;</code>
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      data_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.Payload)
  }

  // @@protoc_insertion_point(class_scope:proto.Payload)
  private static final openfresh.plasma.Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new openfresh.plasma.Payload();
  }

  public static openfresh.plasma.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payload>
      PARSER = new com.google.protobuf.AbstractParser<Payload>() {
    public Payload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Payload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payload> getParserForType() {
    return PARSER;
  }

  public openfresh.plasma.Payload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

