// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfresh/plasma/protobuf/stream.proto

package openfresh.plasma;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.EventType Events = 1;</code>
   */
  java.util.List<openfresh.plasma.EventType> 
      getEventsList();
  /**
   * <code>repeated .proto.EventType Events = 1;</code>
   */
  openfresh.plasma.EventType getEvents(int index);
  /**
   * <code>repeated .proto.EventType Events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .proto.EventType Events = 1;</code>
   */
  java.util.List<? extends openfresh.plasma.EventTypeOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .proto.EventType Events = 1;</code>
   */
  openfresh.plasma.EventTypeOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <code>bool forceClose = 2;</code>
   */
  boolean getForceClose();
}
