// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfresh/plasma/protobuf/stream.proto

package openfresh.plasma;

public final class Stream {
  private Stream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EventType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EventType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&openfresh/plasma/protobuf/stream.proto" +
      "\022\005proto\"?\n\007Request\022 \n\006Events\030\001 \003(\0132\020.pro" +
      "to.EventType\022\022\n\nforceClose\030\002 \001(\010\"\031\n\tEven" +
      "tType\022\014\n\004type\030\001 \001(\t\"<\n\007Payload\022#\n\teventT" +
      "ype\030\001 \001(\0132\020.proto.EventType\022\014\n\004data\030\002 \001(" +
      "\t2?\n\rStreamService\022.\n\006Events\022\016.proto.Req" +
      "uest\032\016.proto.Payload\"\000(\0010\001B\035\n\020openfresh." +
      "plasmaP\001\242\002\006PLASMAb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Request_descriptor,
        new java.lang.String[] { "Events", "ForceClose", });
    internal_static_proto_EventType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_EventType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EventType_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_proto_Payload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Payload_descriptor,
        new java.lang.String[] { "EventType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
